[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
arbitron = "ETjik8Bom7xHKv7HHawVM1igFNwJbKyWBZtnLp8jEkgD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx create-codama-client.ts; npx tsx --test --test-reporter=spec tests/*.ts"

